Learning/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('stock/', include(('stock.urls', 'stock'), namespace='stock')),
    path('login/', auth_views.LoginView.as_view(template_name='admin/login.html'), name='login'),
path('logout/', auth_views.LogoutView.as_view(next_page='stock:list'), name='logout'),
]+ static (settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

stock/urls.py
from django.urls import path
from stock.views import stock_list,stock_detail, stock_buy, account,stock_sell
#!/usr/bin/env python
urlpatterns = [
    path('list/', stock_list, name='list'),
    path('detail/<int:pk>/', stock_detail, name='detail'),
    path('buy/<int:pk>/', stock_buy, name='buy'),
    path('sell/<int:pk>/', stock_sell, name='sell'),
    path('account/', account, name='account'),
]

stock/models.py
from pydoc import describe
from signal import signal
from unicodedata import name
from django.db import models
import random
from django.contrib.auth.models import User

# Create your models here.
class Stock(models.Model):
    name = models.CharField(max_length=40)
    ticker = models.CharField(max_length=4,default="null")
    description = models.TextField(null=True, blank=True)
    currency = models.ForeignKey('Currency', null=True, on_delete=models.SET_NULL)
    logo= models.ImageField(null=True, blank=True)
    def get_random_price(self):
        return random.randint(0,2500)
    def __str__(self):
        return f"{self.ticker}"
        
class Currency(models.Model):
    name = models.CharField(max_length=40)
    ticker = models.CharField(max_length=4)
    sign = models.CharField(max_length=1)
    def __str__(self):
        return self.sign

class Account(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    def __str__(self):
        return self.user.username

class AccountCurrency(models.Model):
    account = models.ForeignKey(Account, on_delete=models.CASCADE)
    currency = models.ForeignKey(Currency, on_delete=models.CASCADE)
    amount = models.IntegerField(default=0)
    class Meta:
        unique_together = ['account', 'currency']
    def __str__(self):
        return f'{self.account.user.username} {self.currency.sign}'

class AccountStock(models.Model):
    account = models.ForeignKey(Account, on_delete=models.CASCADE)
    stock = models.ForeignKey(Stock, on_delete=models.CASCADE)
    amount = models.IntegerField(default=0)
    average_buy_cost = models.DecimalField(null=True, blank=True, decimal_places=2, max_digits=6)
    class Meta:
        unique_together = ['account', 'stock']
    def __str__(self):
        return f'{self.account.user.username} {self.stock.ticker}'

stock/forms.py
from django import forms

class BuySellForm(forms.Form):
    price = forms.DecimalField(widget=forms.NumberInput(attrs={'readonly': 'readonly'}))
    amount = forms.IntegerField()

stock/views.py
from django.shortcuts import render
from stock.models import Stock
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from stock.models import Stock, AccountCurrency, AccountStock
from stock.forms import BuySellForm
from django.core.cache import cache

def stock_list(request):
    stocks=Stock.objects.all()
    context = {
        'stocks':stocks
    }
    return render(request,'stocks.html', context)

@login_required
def stock_detail(request, pk):
    stock = get_object_or_404(Stock, pk=pk)
    context = {
        'stock': stock,
        'form': BuySellForm(initial={'price': stock.get_random_price()})
    }
    return render(request, 'stock.html', context)

@login_required
def stock_buy(request, pk):
    if request.method != "POST":
        return redirect('stock:detail', pk=pk)
    stock = get_object_or_404(Stock, pk=pk)
    form = BuySellForm(request.POST)
    if form.is_valid():
        amount = form.cleaned_data['amount']
        price = form.cleaned_data['price']
        buy_cost = price * amount
        acc_stock, created = AccountStock.objects.get_or_create(account=request.user.account, stock=stock,
                                                                defaults={'average_buy_cost': 0, 'amount': 0})
        current_cost = acc_stock.average_buy_cost * acc_stock.amount
        total_cost = current_cost + buy_cost
        total_amount = acc_stock.amount + amount
        acc_stock.amount = total_amount
        acc_stock.average_buy_cost = total_cost / total_amount
        acc_currency, created = AccountCurrency.objects.get_or_create(account=request.user.account, currency=stock.currency,
                                                                      defaults={'amount': 0})
        if acc_currency.amount < buy_cost:
            form.add_error(None, f'На счёте недостаточно средств в валюте {stock.currency.sign}')
        else:
            acc_currency.amount = acc_currency.amount - buy_cost
            acc_stock.save()
            acc_currency.save()
            return redirect('stock:list')
    context = {
        'stock': get_object_or_404(Stock, pk=pk),
        'form': form
    }
    return render(request, 'stock.html', context)

@login_required
def account(request):
    currencies = [
            {
                'amount': acc_currency.amount,
                'sign': acc_currency.currency.sign
            } for acc_currency in request.user.account.accountcurrency_set.select_related('currency')
    ]
    stocks = [
            {
                'ticker': acc_stock.stock.ticker,
                'amount': acc_stock.amount,
                'avg': acc_stock.average_buy_cost
            } for acc_stock in request.user.account.accountstock_set.select_related('stock').all()
    ]
    context = {
        'currencies': currencies,
        'stocks': stocks
    }
    return render(request, template_name='account.html', context=context)

@login_required
def stock_sell(request, pk):
    if request.method != "POST":
        return redirect('stock:detail', pk=pk)
    stock = get_object_or_404(Stock, pk=pk)
    form = BuySellForm(request.POST)
    if form.is_valid():
        amount = form.cleaned_data['amount']
        price = form.cleaned_data['price']
        form.add_error(None,{})
        sell_cost = price * amount
        acc_stock, created = AccountStock.objects.get_or_create(account=request.user.account, stock=stock,
                                                                defaults={'amount': 0})
        acc_currency, created = AccountCurrency.objects.get_or_create(account=request.user.account, currency=stock.currency,
                                                                      defaults={'amount': 0})
        if acc_stock.amount < amount:
            form.add_error(None, f'На счёте недостаточно акций')
        elif amount<=0:
            form.add_error(None, f'Неверное количество акций')
        else:
            acc_currency.amount = acc_currency.amount + sell_cost
            acc_stock.amount = acc_stock.amount - amount
            acc_stock.save()
            acc_currency.save()
            return redirect('stock:list')
    context = {
        'stock': get_object_or_404(Stock, pk=pk),
        'form': form
    }
    return render(request, 'stock.html', context)

stock/templates/account.html
{% extends 'base.html' %}
{% block content %}
    <div>
        <h4>Денежные средства</h4>
        {% for acc_currency in currencies %}
            <div>{{ acc_currency.amount }}{{ acc_currency.sign }}</div>
        {% endfor %}
    </div>
    <div>
        <h4>Акции</h4>
        {% for acc_stock in stocks %}
            <div>{{ acc_stock.ticker }} - {{ acc_stock.amount }} - {{ acc_stock.avg }}</div>
        {% endfor %}
    </div>
    <div>
        <a href="{% url 'stock:list' %}">К списку акций</a>
    </div>
{% endblock %}

stock/templates/base.html
{% load static %}
<!doctype html>
<html lang="ru">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Список акций</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" />
  </head>
  <body>
    <main>
      <div class="py-5 bg-light">
        <div class="container">
          <div class="row row-cols-1">
            <div class="col">
              {% if user.is_authenticated %}
              <span>Добро пожаловать, {{ user.username }}</span> | <a href="{% url 'stock:account' %}">Личный кабинет</a> | <a href="{% url 'logout' %}">Выход</a>
              {% else %}
                <a href="{% url 'login' %}">Вход</a>
              {% endif %}
            </div>
          </div>
        </div>
      </div>                       
      <div class="py-5 bg-light">
        <div class="container">
          <div class="row row-cols-1">
            <div class="col">
              {% block content %}{% endblock %}
            </div>
          </div>
        </div>
      </div>
    </main>
    <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
  </body>
</html>

stock/templates/stock.html
{% extends 'base.html' %}
{% block content %}
    <div>
        Акции {{ stock.name }} ({{ stock.ticker }}) <img src="{{ MEDIA_URL }}/{{ stock.logo }}" width="40" />
    </div>
    <div>
        <form method="POST">
            {% csrf_token %}
            {{ form }}
            <button formaction="{% url 'stock:buy' stock.pk %}" >Купить</button>
            {% csrf_token %}
            <button formaction="{% url 'stock:sell' stock.pk %}" >Продать</button>
        </form>
    </div>
    <div>
        <a href="{% url 'stock:list' %}">Назад к списку</a>
    </div>
{% endblock %}

stock/templates/stocks.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>List of Stocks</title>
</head>
<body>
    {% extends 'base.html' %}
    {% block content %}
    <table class="table">
        <thead>
            <tr>
                <th>Logo</th>
                <th>Ticker</th>
                <th>Company</th>
                <th>Last close price</th>
            </tr>
        </thead>
        <tbody>
        {% for stock in stocks %}
            <tr>
                <td> 
                    {% if stock.logo %}
                    <img src="{{ MEDIA_URL }}/{{ stock.logo }}" width="40" />
                    {% endif %}
                </td>
                <td>{{ stock.ticker }}</td>
                <td>{{ stock.name }}</td>
                <td>{{ stock.get_random_price }}{{ stock.currency.sign }}</td>
                <td><a href="{% url 'stock:detail' stock.pk %}">Купить/Продать</a></td> 
            </tr>
        {% endfor %}
        </tbody>
    </table>
    {% endblock %}
</body>
</html>